### PR TITLE
Update hterm to 1.80 and fix copying and pasting

### LINKED ISSUE #49: Upgrade to hterm1.80
From exploration on https://github.com/OSC/ood-shell/issues/48, it looks like some code modifications are required after this update.

### PR DESCRIPTION
**Pull request by laser505t**
Fixes #49, #48 

Old:
>Works! But no better with pasting in Firefox. In fact, there is now no little red cursor in Firefox.
>I haven't removed the old version yet, so don't merge until more testing takes place.
>I built this version from source at the hterm-1.80 tag because I couldn't find a prebuilt version. I'm not sure why @MorganRodgers wasn't able to get it to work with a symlink in #48.

### CODE REVIEW

**Comment by laser505t** [comment]
I can't believe I didn't try this sooner, but it somehow works with a little bit of configuration change. I'd always assumed it would have the same pasting behavior except with a different keystroke (Ctrl+V instead of Ctrl+Shift+V). Copying now works with Ctrl+C. However, simply selecting text does not copy like it does in Chrome (when the scissors icon comes up). The only potential issue may be when the user wants Ctrl+C to be sent to the running program. It should suffice to use Ctrl+Shift+C instead to send that signal, but when I run `cat` (where input is from the keyboard and not a file), a simple Ctrl+C will terminate it.
Side note: it seems that hterm 1.81 will not work, unless Owens provided some faulty build tools. I had to use `module load python/3.6` to run the mkdist.sh script.

**Comment by ericfranz** [comment]
You should be building on the webnode using software collections node, not Owens.

Also why did the fix to copy require rebuilding public/javascripts/hterm_all_1.80.js. Did you make a modification to the actual herm code?

**Comment by MorganRodgers** [comment]
@ericfranz the hterm git repo doesn't ship that file, it has to be either built or downloaded by one of the Node package managers.

**Comment by ericfranz** [comment]
Yes and 53e8c61 updated hterm to 1.80. So I would expect the fix to copying and pasting in 71cc9c0 would not result in a rebuild of hterm 1.80 but it does. So the question is why? Is it because to fix copying and pasting the hterm source code was modified? If so we need to understand what the change is and if we can apply that change without changing the hterm source code.

**Comment by laser505t** [comment]
Building hterm 1.81 on webtest04 made no difference to the resulting js file, except it changed the build date and time. Here the js console output from webtest04 when using hterm 1.81:

image

I guess it's all client side, so having the newer version of Node.js doesn't help. And it doesn't seem to depend on Node.js during build time because I only did an scl enable rh-python35.

**Pull request merged**
