### PR TITLE
Use global environment file

### LINKED ISSUE #42: Move config to /etc
Possible solution:

```diff
// Set dotenv as early as possible
-require('dotenv').config();
+var dotenv = require('dotenv');
+dotenv.config({path: ".env.local"})
+dotenv.config({path: "/etc/ood/config/apps/shell/.env"})
+dotenv.config();
```

Since there is only a small set of env vars, we can just set them all in each. So no need to "modify location of /etc/ood/config/apps". (probably wondering why we didn't do this in every OOD app...)

### PR DESCRIPTION
**Pull request by nickjer**
Fixes #42 

Reads configuration from:

- `/etc/ood/config/apps/shell/config.yml`
- `.env.local`
- `/etc/ood/config/apps/shell/env`
- `.env`

ordered by prioritization.

The location of the YAML configuration file can be overridden with env var `OOD_CONFIG`.

Extra things added:

- added deprecation warnings
- added example YAML configuration file to be copied to global location

screenshot from 2017-11-07 16-28-48

### CODE REVIEW

**Comment by ericfranz** [comment]
What's the rationale for adding the yaml config file?

**Comment by ericfranz** [comment]
All that sounds great, except I think we should hold off on this change for the Shell app right now for this reason:

>I just think it is more beneficial in the long run to use a single YAML configuration file for options we expect sys admins will want to configure. And introducing it as early as possible helps drive adoption.

IMHO a single YAML configuration file for Open OnDemand core is desirable, not a separate configuraiton file for each app or component. Also, I don't think that this is true:

>And introducing it as early as possible helps drive adoption.

When we introduce a new format and location for configuration and deprecate the old, we will document it in the upgrade directions (or even provide automated conversion from old to the new).

It is less costly in the short term to just keep doing the env vars, however. Most of the benefits you mention don't really impact the shell app at all (nor the files app); they are more relevant like you say as OOD as a whole.

**Comment by nickjer** [comment]
1. There is no commit that only adds the env changes that can be cherry-picked. Although it is pretty simple to remove the `config.yml` changes (or comment them out).
2. Maybe we should call the env var `OOD_APP_ENV` and have it default to `/etc/ood/config/apps/shell/env` if unset. That way we can save `OOD_CONFIG` or `OOD_APP_CONFIG` for any YAML configuration file we use in the future and maintain backwards compatibility.

**Comment by ericfranz** [comment]
I was going to use OOD_APP_CONFIG for My Jobs and Dashboard, as in those cases we want to configure the application specific configuration directory, versus the configuration file. So if we used that convention across the board we would use OOD_APP_CONFIG here for /etc/ood/config/apps/shell. Reason I like OOD_APP_CONFIG better is when I think of OOD_CONFIG I think of /etc/ood/config. Though the only use case of changing the entire config directory location is when I want the entire config directory to be in my home directory, like when I installed apps and wanted to test configuration at TSC, including the cluster config, and for the few times we do that it probably is the same amount of work to tell each app to look at custom location for their config (drop a .env.local file in each app directory, and set OOD_CONFIG or OOD_APP_CONFIG => though in the case of OOD_CONFIG you can use the same .env.local for everyone).

**Comment by ericfranz** [comment]
To clarify, if `OOD_APP_CONFIG=/etc/ood/config/apps/shell` then the env file now would be OOD_APP_CONFIG + "/env" and a yaml later could be OOD_APP_CONFIG + "/config.yml". Of course if we use one shared yaml config file for all the core OOD apps, that makes this decision irrelevant.

**Comment by nickjer** [comment]
Setting `OOD_APP_CONFIG` to be a directory with an opinionated file/directory structure underneath has a couple of drawbacks:

- To modify just the global `env` file you will need to copy down the entire global config root (initializers and all) into your custom `OOD_APP_CONFIG` directory (the reverse of this is also true if you want to just edit the initializers).
- This one is more of an edge case: A sys admin cannot point to a different location on the file system for the initializers from within the global `env` file.

One suggestion is to use:

- `OOD_APP_ENV` - path to global `env` file
- `OOD_APP_INITIALIZERS_ROOT` - path to global initializers root directory

**Comment by nickjer** [comment]
Also another benefit to using an env var that points directly to the `env` file (as opposed to a directory) is that I won't need to create a directory every time I want to create an experimental `env` file in the root of my app.

**Comment by ericfranz** [comment]
>This one is more of an edge case: A sys admin cannot point to a different location on the file system for the initializers from within the global env file.

If a sys admin wants to configure an app config location in /etc/ I would think that the place to do that would be /etc/ood/profile.

> To modify just the global env file you will need to copy down the entire global config root (initializers and all) into your custom OOD_APP_CONFIG directory (the reverse of this is also true if you want to just edit the initializers).

I'm okay with this drawback. App configuration originally went in the APPROOT. What all these changes are effectively doing is adding another path to look for configuration specified by 
APP_CONFIG_ROOT.

A .env.local can set APP_CONFIG_ROOT as well.

**Comment by ericfranz** [comment]
The drawback of the other approach is we now have multiple env variables, one for each extra config file. First its OOD_APP_ENV. Then OOD_APP_INITIALIZERS_ROOT. Then OOD_APP_LIB_ROOT. Then OOD_APP_CONFIG_YAML. etc. Its simpler to just have one other path to look for configuration.

**Comment by nickjer** [comment]
In short, the argument for separate environment variables is mostly for development purposes.

I like the control multiple env vars gives us so that I can develop the Dashboard in the same environment it will be running in:

- develop `env` only by pointing to a custom `env`
- develop intializers only by pointing to a custom directory
- develop the app only, so point to global `env` and initializers

> The drawback of the other approach is we now have multiple env variables, one for each extra config file.

This is actually fairly common in Linux. You have `PATH` for binaries and `LD_LIBRARY_PATH` for libraries (there is also `CPATH` if you want to change the includes path for compiling). If you choose good defaults then it is very rare a sys admin would ever need to alter these (so they wouldn't care for them), only developers will want to alter them depending on what they want to develop.

Currently the Dashboard will only need an environment file and an initializers directory, so specifying them as separate environment variables doesn't cause too much overhead but gives more flexibility in the long run.

Another alternative is having all of them:

- OOD_APP_ENV
- OOD_APP_INITIALIZERS_ROOT
- OOD_APP_CONFIG_ROOT

listed in order of priority. So if `$OOD_APP_ENV` is undefined it tries `$OOD_APP_CONFIG_ROOT/env`.

**Comment by nickjer** [comment]
If we go the route of a single `production` env:

```
/etc/ood/config/apps/<app_name>/env
```

and a single `development` env:

```
./.env.local
```

Then that simplifies things greatly because `OOD_APP_ENV` and `OOD_APP_CONFIG` would be irrelevant. Then all you'd need is `OOD_APP_INITIALIZERS_ROOT`, which defaults for `production` to:

```
/etc/ood/config/apps/<app_name>/initializers
```

and for development it is undefined unless the developer defines it.

**Pull request merged**
